---
- hosts: Docker
  become_user: root
  roles:
    - Docker
- hosts: node_exporter
  # become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: prometheus
  # become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: grafana
  # become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana
- hosts: loki
  # become: yes
  become_user: root
  become_method: sudo
  roles:
    - loki
